// @ts-nocheck
// This file is autogenerated by scripts/bchynld-registry.ts
// Do not edit this file directly.
import * as React from "react"

export const Index: Record<string, any> = {
  default: {
    "input-erc20": {
      name: "input-erc20",
      type: "components:chyn",
      registryDependencies: undefined,
      component: React.lazy(() => import("@/registry/default/chyn/input-erc20")),
      files: ["registry/default/chyn/input-erc20.tsx"],
    },
    "input-erc20-demo": {
      name: "input-erc20-demo",
      type: "components:example",
      registryDependencies: ["input"],
      component: React.lazy(() => import("@/registry/default/example/input-erc20-demo")),
      files: ["registry/default/example/input-erc20-demo.tsx"],
    },
    "input-erc20-form": {
      name: "input-erc20-form",
      type: "components:example",
      registryDependencies: ["input"],
      component: React.lazy(() => import("@/registry/default/example/input-erc20-form")),
      files: ["registry/default/example/input-erc20-form.tsx"],
    },
  }
}
